gitSafeReplacementChar: '-'
branchName: 'AUA-${issue.number}-${issue.title,}'
branches:
  - label: enhancement
    prefix: feature/
    skip: false
  - label: documentation
    prefix: feature/
    skip: false
  - label: bug
    prefix: bugfix/
    skip: false
  - label: *
    skip: true
