gitSafeReplacementChar: '-'
branchName: 'AUA-${issue.number}-${issue.title,}'
branches:
  - label: 'new feature', 'good first issue'
    prefix: feature/
    skip: false
  - label: enhancement
    prefix: hotfix/
    skip: false
  - label: documentation
    prefix: feature/
    skip: false
  - label: bug
    prefix: bugfix/
    skip: false
  - label: '*'
    skip: true
